id: P007981
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25770
  title: ཚངས་མགུར་ཞིབ་འཇུག
  author: ''
  volumes:
    e20ccba49983464ab95e4740d9bf655d:
      image_group_id: I1KG25772
      title: ''
      volume_number: 1
      total_pages: 258
ebook_metadata:
  title: ཚངས་མགུར་ཞིབ་འཇུག
  author: ''
  sku: P007981
  cover: cover.jpg
  layers:
  - pagination
