id: P007981
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG25770
  title: ཚངས་མགུར་ཞིབ་འཇུག
  author: ''
  volumes:
    db55533355ca4f61945a74ac7913549b:
      image_group_id: I1KG25772
      title: Volume 1 of tshangs mgur zhib 'jug
      volume_number: 1
      total_pages: 258
      base_file: v001.txt
